### ISSUE TITLE
Enfold Config file

### ISSUE THREAD

**Issue by InoPlugs** [OnTheGoSystems/wpml-config#24]
Hi,

not sure, but a team mate told me that you updated the config file

https://git.onthegosystems.com/wpml-public/wpml-config/blob/master/enfold/wpml-config.xml

But there is an important difference - check `<custom-fields>`

https://github.com/OnTheGoSystems/wpml-config/blob/master/enfold/wpml-config.xml

The other sections I did not check.

**Comment by amElnagdy** [comment]
Hi @InoPlugs 
This is the one that's working https://github.com/OnTheGoSystems/wpml-config/blob/master/enfold/wpml-config.xml
Please ignore https://git.onthegosystems.com/wpml-public/wpml-config/blob/master/enfold/wpml-config.xml

Thanks!

**Comment by InoPlugs** [comment]
Hi @amElnagdy 

Thanks for the info.
