### ISSUE TITLE
[Enfold][High Priority BUG] ALB no longer works with WP > 5.0 and Translation Management

### ISSUE THREAD

**Issue by InoPlugs** [OnTheGoSystems/wpml-config#75]
@amElnagdy 

Seems to be a serious problem:

WPML Version 4.2.1
WPML Translation Management Version 2.8.1
WP 5.0.3
Enfold 4.5.4

Classic Editor plugin does not make any difference
Enfold Theme Options Tab setting Classic/Block Editor no difference

- Create a new page using a few ALB Elements
- Translate this page using the translation management
- Open the original page in frontend -> OK
- Open the translated page -> empty
- Opening in backend all seems OK
--------

In Database most of the meta data for the ALB are missing.

When saving the translation content you no longer are calling the standard WP filter save_post/wp_insert_post which we use to hook and save the metabox fields.

As we rely on updating our shortcode tree and aviaBuilder_cleanData field (and some other stuff) this will break everything.

I had a quick look into your code doing the save - based on Backbone - but I've never used backbone till now.

Can you provide a filter/action where we can hook into to get all data we normally had when a post was saved prior to WP 5.0 ?

**Comment by dgwatkins** [comment]
You can try with the `wpml_tm_save_post` action.

**Comment by InoPlugs** [comment]
@amElnagdy @dgwatkins 

This action does not help because it is only fired when using the "normal" edit page - and in this case the standard WP filter also work.

If you open the translation page e.g. with the pencil from the page screen, edit the text and click "Save and close" or "save" we need a chance to hook.

**Comment by dgwatkins** [comment]
I just checked the actions called during a "Save and close" and the `save_post` action is being called twice. I suspect it is once for the revision and again for the new version of the post.

`wp_insert_post` is also called twice, as expected.

The problem may be a different one but I don't have enough information to find out.
Can you describe the problem you are having with ALB and how I can replicate it?

**Comment by amElnagdy** [comment]
@InoPlugs could you please check out this [small screencast](https://drive.google.com/file/d/1PjM8g6qHFIlxXcDWg5pSiUW4oJ45f-OT/view?usp=sharing)? I can't replicate your issue following the steps from op. Could you please check if I'm doing something wrong?

**Comment by InoPlugs** [comment]
@amElnagdy 

Environment:

WPML Version 4.2.1
WPML Translation Management Version 2.8.1
WP 5.0.3
Enfold 4.5.4

Thanks for looking into.

Strange - exactly the same steps as I do - but it does not work for me in frontend.
And also checking the meta data shows empty shortcode tree _avia_builder_shortcode_tree and missing alb data for translated post- except _aviaLayoutBuilder_active.

I could locate that we do not catch the hooks wp_insert_post_data and. 'save_post' when you save the translation. 

Adding the filter that it is called I can see the post content - but the filter is called 2 times inside wpml_save_job_ajax action.

To me it seems that the post content contains the correct translated elements - means that we can build all meta information we need. 

I think we should be safe doing that.

**Comment by amElnagdy** [comment]
@InoPlugs I had a different environment 
WP 5.1
Enfold 4.5.4.1
and most importantly, WPML development versions.

Would you like to test this in a shared environment? You'll receive an email from http://enfold.compatibility.wpml.org , you can try to reproduce the issue there.

**Comment by InoPlugs** [comment]
@amElnagdy 

Yes please - send me the details at support@inoplugs.com

**Comment by amElnagdy** [comment]
Sent, @InoPlugs

**Comment by InoPlugs** [comment]
@amElnagdy 

Thanks for the login credentials. I tried to reproduce on your site - it works 👍 

Could you send me a copy of the 4 plugins that you are currently running on this server to make sure it is really fixed also on my dev environment- will setup WP 5.1 and latest versions.

Thanks :)

**Comment by InoPlugs** [comment]
@amElnagdy 

Forgot to mention the plugins:

WPML Multilingual CMS
WPML Translation Management
WPML String Translation
WPML Media

**Comment by amElnagdy** [comment]
@InoPlugs sent via email :)

**Comment by InoPlugs** [comment]
@amElnagdy 

Thanks for the files.

FYI: This version now also works on my install. 👍 

Have setup a clean WP install and WP 5.0.3.
